apiVersion: v2
name: mailmate
description: MailMate - WhatsApp-powered email, calendar & tracking assistant
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - whatsapp
  - email
  - calendar
  - chatbot
maintainers:
  - name: hmntkpr
